from interfaces import gui
from interfaces.reader_interface import ChatReaderInterface
from interfaces.wathcer_interface import ChatWatcherInterface
from interfaces.writer_interface import ChatWriterInterface
